void display_array(int *,int);
void swap(int *,int *);
void bubble_sort(int *,int,int);
void insertion_sort(int *,int,int);
int pivot(int *,int ,int ,int);
void quick_sort(int *,int,int,int);
void merge(int *,int,int,int,int);
void merge_sort(int *,int,int,int);
void build_heap(int *,int);
void max_heapify(int *,int,int);